### ISSUE TITLE
Move to parity.js

### ISSUE THREAD

**Issue by jennazenk** [melonproject/melon.js#77] opened 2017-10-27 00:06 UTC

**Comment by jennazenk** [comment] 2017-10-27 00:08
Think this one is the right repo: https://github.com/paritytech/js-api

**Comment by schmidsi** [comment] 2017-11-08 13:27
Should work with https://github.com/paritytech/js-api/issues/6

Other features that we need that I don't know if parity.js supports it:
- [ ] Parsing raw events
- [ ] In-Browser account management (independent of MetaMask or a running parity node)
- [ ] Blockstream?

**Comment by schmidsi** [comment] 2017-11-08 13:31
Duplicate of #69

**Closed by schmidsi** 2017-11-08 13:31 UTC
Labels: duplicate
